In [13]:
import pandas as pd

In [14]:
may_df = pd.read_csv("citibike_may_21.csv")

may_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45038,62FF3FEDAAD7FCB3,docked_bike,2021-05-31 12:46:22,2021-05-31 12:52:29,Clinton St & 7 St,HB303,7 St & Monroe St,HB304,40.745420,-74.033320,40.746413,-74.037977,casual
45039,E742AEA7068E0E4A,docked_bike,2021-05-31 16:34:19,2021-05-31 16:59:21,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45040,E769F9EE96D6433A,docked_bike,2021-05-17 22:52:35,2021-05-17 23:13:37,Astor Place,JC077,Astor Place,JC077,40.719282,-74.071261,40.719282,-74.071262,casual
45041,EC973614DCA179A2,docked_bike,2021-05-31 20:48:58,2021-05-31 21:16:02,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45042,3571180FE5C52CB1,docked_bike,2021-05-23 14:28:43,2021-05-23 14:30:59,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual

In [3]:
june_df = pd.read_csv("citibike_june_21.csv")

In [4]:
july_df = pd.read_csv("citibike_july_21.csv")

In [7]:
month_list = [may_df, june_df, july_df]  # List of your dataframes
all_months_df = pd.concat(month_list)
g_bike = all_months_df.groupby("rideable_type").count()

In [9]:
citi_bike_df = all_months_df.to_csv("all_months_citibike.csv")

citi_bike_df

NameError: name 'df' is not defined