In [1]:
import pandas as pd

import datetime as dt

import numpy as np

In [2]:
may_df = pd.read_csv("citibike_may_21.csv")

may_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45038,62FF3FEDAAD7FCB3,docked_bike,2021-05-31 12:46:22,2021-05-31 12:52:29,Clinton St & 7 St,HB303,7 St & Monroe St,HB304,40.745420,-74.033320,40.746413,-74.037977,casual
45039,E742AEA7068E0E4A,docked_bike,2021-05-31 16:34:19,2021-05-31 16:59:21,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45040,E769F9EE96D6433A,docked_bike,2021-05-17 22:52:35,2021-05-17 23:13:37,Astor Place,JC077,Astor Place,JC077,40.719282,-74.071261,40.719282,-74.071262,casual
45041,EC973614DCA179A2,docked_bike,2021-05-31 20:48:58,2021-05-31 21:16:02,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45042,3571180FE5C52CB1,docked_bike,2021-05-23 14:28:43,2021-05-23 14:30:59,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual

In [3]:
june_df = pd.read_csv("citibike_june_21.csv")

june_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7830EBE775F2EE25,classic_bike,2021-06-21 07:38:42,2021-06-21 10:49:25,Dixon Mills,JC076,NaN,NaN,40.721630,-74.049968,NaN,NaN,member
1,629A3BFD50BF8392,docked_bike,2021-06-12 10:25:01,2021-06-12 10:35:11,Dixon Mills,JC076,Journal Square,JC103,40.721630,-74.049967,40.733670,-74.062500,member
2,CF02EC434989A99D,docked_bike,2021-06-07 14:52:05,2021-06-07 14:58:25,11 St & Washington St,HB502,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.749984,-74.027150,40.735938,-74.030305,member
3,E1BB8FED29AA5BA1,docked_bike,2021-06-07 08:29:19,2021-06-07 08:34:17,8 St & Washington St,HB603,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.745983,-74.028199,40.735938,-74.030305,casual
4,787C59EE76D96BCA,docked_bike,2021-06-18 14:16:27,2021-06-18 14:26:26,11 St & Washington St,HB502,Columbus Park - Clinton St & 9 St,HB501,40.749984,-74.027150,40.748161,-74.032453,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71437,837E135024442757,docked_bike,2021-06-06 22:07:08,2021-06-06 22:13:46,Morris Canal,JC072,Warren St,JC006,40.712418,-74.038525,40.721124,-74.038051,member
71438,14F127B834A8ED72,docked_bike,2021-06-20 20:53:48,2021-06-20 21:00:44,Morris Canal,JC072,Warren St,JC006,40.712418,-74.038525,40.721124,-74.038051,member
71439,A9FE39A9E76C2192,docked_bike,2021-06-01 21:27:29,2021-06-01 21:36:04,Morris Canal,JC072,Warren St,JC006,40.712418,-74.038525,40.721124,-74.038051,member
71440,E0FCE3CE0160B4E0,docked_bike,2021-06-11 15:22:44,2021-06-11 15:30:18,Morris Canal,JC072,Warren St,JC006,40.712418,-74.038525,40.721124,-74.038051,member
71441,B342E07B460305A1,docked_bike,2021-06-06 23:22:42,2021-06-06 23:28:04,Morris Canal,JC072,Warren St,JC006,40.712418,-74.038525,40.721124,-74.038051,member

In [4]:
july_df = pd.read_csv("citibike_july_21.csv")

july_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C9446233AFAB8896,classic_bike,2021-07-15 19:27:25,2021-07-15 19:27:35,Journal Square,JC103,Journal Square,JC103,40.733670,-74.062500,40.733670,-74.062500,member
1,0C3D69370BE39992,electric_bike,2021-07-22 06:41:54,2021-07-22 06:42:03,Journal Square,JC103,Journal Square,JC103,40.733670,-74.062500,40.733670,-74.062500,member
2,3B0390B706281176,classic_bike,2021-07-19 06:36:13,2021-07-19 06:38:18,Brunswick & 6th,JC081,Jersey & 6th St,JC027,40.726012,-74.050389,40.725289,-74.045572,member
3,9AFBC07247ABE507,classic_bike,2021-07-08 06:33:45,2021-07-08 06:35:53,Brunswick & 6th,JC081,Jersey & 6th St,JC027,40.726012,-74.050389,40.725289,-74.045572,member
4,ADB073F7FFC372D3,classic_bike,2021-07-21 07:33:49,2021-07-21 08:00:14,14 St Ferry - 14 St & Shipyard Ln,HB202,Columbus Dr at Exchange Pl,JC106,40.752961,-74.024353,40.716870,-74.032810,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82573,3EC1B265DBD89895,classic_bike,2021-07-31 17:01:57,2021-07-31 17:10:55,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,casual
82574,6D6303B3D638B24C,electric_bike,2021-07-21 09:12:09,2021-07-21 09:22:46,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,casual
82575,CC8F22DE9DA05F09,electric_bike,2021-07-19 18:51:33,2021-07-19 18:58:26,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,casual
82576,A846B2B1CECD7F09,classic_bike,2021-07-19 20:45:41,2021-07-19 20:47:56,Columbus Drive,JC014,Warren St,JC006,40.718355,-74.038914,40.721124,-74.038051,casual
82577,37858A6DFC7A9A88,classic_bike,2021-07-10 16:06:35,2021-07-10 16:52:29,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,member

In [5]:
month_list = [may_df, june_df, july_df]  # List of your dataframes
all_months_df = pd.concat(month_list)
g_bike = all_months_df.groupby(["start_station_id","end_station_id"]).count()

bike_new_index = g_bike.reset_index()

In [6]:
bike_new_index

all_months_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82573,3EC1B265DBD89895,classic_bike,2021-07-31 17:01:57,2021-07-31 17:10:55,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,casual
82574,6D6303B3D638B24C,electric_bike,2021-07-21 09:12:09,2021-07-21 09:22:46,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,casual
82575,CC8F22DE9DA05F09,electric_bike,2021-07-19 18:51:33,2021-07-19 18:58:26,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,casual
82576,A846B2B1CECD7F09,classic_bike,2021-07-19 20:45:41,2021-07-19 20:47:56,Columbus Drive,JC014,Warren St,JC006,40.718355,-74.038914,40.721124,-74.038051,casual
82577,37858A6DFC7A9A88,classic_bike,2021-07-10 16:06:35,2021-07-10 16:52:29,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,member

In [88]:
null_df = all_months_df.isnull()

clean_all_months = all_months_df.dropna()

new_df2 = clean_all_months.groupby("start_station_name").min()

# casual_df = clean_all_months.loc[clean_all_months["member_casual"] == "casual"]

# member_df = clean_all_months.loc[clean_all_months["member_casual"] == "member"]

# casual_df.set_index("start_station_name")

new_df2

,ride_id,rideable_type,started_at,ended_at,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
start_station_name,,,,,,,,,,,,
11 St & Washington St,0001EE0246F27103,classic_bike,2021-05-03 17:17:16,2021-05-03 18:10:27,HB502,10 Ave & W 14 St,4821.06,40.749984,-74.027150,40.699918,-74.078900,casual
14 St Ferry - 14 St & Shipyard Ln,002C3CF3E100762C,classic_bike,2021-06-18 13:32:03,2021-06-18 13:48:05,HB202,11 St & Washington St,4846.01,40.752960,-74.024353,40.701221,-74.083639,casual
2 St HBLR - 2 St & Marshall St,00A5676ADDF57346,classic_bike,2021-05-13 16:36:19,2021-05-13 16:42:32,HB403,11 St & Washington St,6765.01,40.740801,-74.042435,40.711130,-74.083639,casual
4 St & Grand St,00516C6D0798213F,classic_bike,2021-05-20 21:31:33,2021-05-20 22:21:00,HB301,11 St & Washington St,5175.08,40.742257,-74.035111,40.711066,-74.071959,casual
5 Corners Library,00626095043DCF3D,classic_bike,2021-05-01 14:24:12,2021-05-01 14:50:15,JC018,11 St & Washington St,HB101,40.734961,-74.059503,40.706575,-74.086701,casual
...,...,...,...,...,...,...,...,...,...,...,...,...
Union St,002FE86200809B4C,classic_bike,2021-05-02 09:26:46,2021-05-02 10:10:38,JC051,5 Corners Library,HB101,40.718211,-74.083639,40.706575,-74.086701,casual
Van Vorst Park,0012E9D014749D35,classic_bike,2021-05-01 07:04:52,2021-05-01 07:06:54,JC035,11 St & Washington St,HB101,40.718488,-74.047727,40.706575,-74.086701,casual
Warren St,004826C1DE7A222B,classic_bike,2021-05-01 08:32:18,2021-05-01 08:34:57,JC006,11 St & Washington St,5297.02,40.721123,-74.038051,40.709198,-74.083639,casual
Washington St,000B52A651859FEA,classic_bike,2021-05-01 01:51:41,2021-05-01 01:58:52,JC098,11 St & Washington St,5001.08,40.724294,-74.035483,40.705693,-74.086701,casual
Willow Ave & 12 St,0029AEF7A1A61DDA,classic_bike,2021-07-02 21:16:13,2021-07-02 21:26:47,HB505,11 St & Washington St,6398.06,40.751867,-74.030377,40.714145,-74.051789,casual

In [8]:
citi_bike_df = clean_all_months.to_csv("all_months_citibike.csv")

citi_bike_df

In [9]:
null_df = all_months_df.isnull()

clean_all_months = all_months_df.dropna()

clean_all_months(pd.to_datetime()

TypeError: to_datetime() missing 1 required positional argument: 'arg'

In [ ]:
april_19 = pd.read_csv("citibike_april_19.csv")

In [ ]:
may_19 = pd.read_csv("citibike_may_19.csv")

In [ ]:
june_19 = pd.read_csv("citibike_june_19.csv")

In [ ]:
month_list = [april_19, may_19, june_19]

all_month_19 = pd.concat(month_list)

all_month_19

In [ ]:
all_month_19.loc[all_month_19['gender'] != 0]

all_month_19

all_month_no_0 = all_month_19.loc[(all_month_19 != 0).all(axis=1), :]

all_month_no_0

In [ ]:
all_months_19 = all_month_no_0.to_csv("citibike_3_months.csv")